# Generated by Django 5.0.7 on 2024-07-11 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='sponsor',
            field=models.ForeignKey(limit_choices_to={'status': 'Tasdiqlangan'}, on_delete=django.db.models.deletion.PROTECT, related_name='agreement', to='users.sponsor'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreement', to='users.student'),
        ),
    ]
